// On docs.rs (which sets `--cfg docsrs`) opt into the nightly `doc_cfg` feature so items gated
// behind a Cargo feature render an "Available on crate feature ..." banner in the docs.
#![cfg_attr(docsrs, feature(doc_cfg))]
#![warn(missing_docs)]

//! A strongly typed Event Tracing for Windows wrapper.
//!
//! The `gen_etw_wrapper!` macro turns an ETW manifest into a strongly typed provider struct.
//! This crate supports Windows only.
//!
//! ```no_run
//! # #[cfg(feature = "macro")]
//! use etw_wrapper::{Result, gen_etw_wrapper};
//!
//! # #[cfg(feature = "macro")]
//! gen_etw_wrapper!("manifests/widgetservice.man", PROVIDER_WIDGETSERVICE -> WidgetLogger);
//!
//! # #[cfg(feature = "macro")]
//! fn main() -> Result<()> {
//!     let provider = WidgetLogger::register()?;
//!     provider.request_failed(0x12ABCDEF, 500, 42, "failed to succeed")?;
//!     Ok(())
//! }
//! # #[cfg(not(feature = "macro"))]
//! # fn main() {}
//! ```
//!
//! To avoid the procedural macro, call [`EtwLogger::register`], optionally check
//! [`EtwLogger::enabled`] before [`EtwLogger::write`], and convert parameters to
//! [`EventDataDescriptor`](field::EventDataDescriptor) instances with the helpers in the
//! [`field`] module.
//!
//! ```no_run
//! use etw_wrapper::{EtwLogger, EventDescriptor, Guid, field::*};
//! let ctx = EtwLogger::register(&Guid::default()).unwrap();
//! let x = 1u32;
//! let y = to_u16cstring("hello");
//!
//! let descriptor = EventDescriptor::default();
//! ctx.write(&descriptor, &[scalar(&x), str16(&y).unwrap()]).unwrap();
//! ```

#[cfg(feature = "macro")]
#[cfg_attr(docsrs, doc(cfg(feature = "macro")))]
pub use etw_wrapper_macro::gen_etw_wrapper;

// Gives generated code a stable path when the macro is invoked from this package's own targets.
extern crate self as etw_wrapper;

// Vendored Win32 declarations generated by `cargo xtask regenerate-bindings`.
#[allow(non_snake_case, non_camel_case_types, dead_code, clippy::all)]
#[allow(missing_docs)]
mod bindings;
mod context;
mod error;
pub mod field;
mod types;

pub use context::EtwLogger;
pub use error::{Error, Result};

// These crate-owned types keep callers independent of any `windows` crate version.
/// Describes an ETW event's identity and filtering metadata.
pub use types::EventDescriptor;
/// A Windows file time represented as 100-nanosecond intervals since January 1, 1601 UTC.
pub use types::FileTime;
/// A Windows globally unique identifier.
pub use types::Guid;
/// A Windows date and time with millisecond precision.
pub use types::SystemTime;

// `windows-bindgen` uses this referenced Win32 name in the private declarations it generates.
#[allow(non_camel_case_types)]
pub(crate) type EVENT_DESCRIPTOR = EventDescriptor;

// Callers build payloads with `field::EventDataDescriptor`, which borrows the data it points at.
// The raw type stays internal because its union field type is not nameable outside this crate.
pub(crate) use types::EVENT_DATA_DESCRIPTOR;
