[package]
name = "etw-wrapper"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Strongly typed Event Tracing for Windows (ETW) logger generation"
documentation = "https://docs.rs/etw-wrapper"

[dependencies]
etw-wrapper-macro = { version = "0.1", optional = true, path = "../etw-wrapper-macro" }
windows = { workspace = true }
safe-sid = { workspace = true }

[features]
default = ["macro"]
macro = ["dep:etw-wrapper-macro"]

[[example]]
name = "example"
required-features = ["macro"]

[[test]]
name = "all_types"
required-features = ["macro"]

[[test]]
name = "arrays"
required-features = ["macro"]

[[test]]
name = "fieldref"
required-features = ["macro"]

[[test]]
name = "hex"
required-features = ["macro"]

[dev-dependencies]
windows = { workspace = true }

